### ISSUE TITLE
quick search with combined/auto using oid

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/splash_page#49]
Can we switch the order of steps when someone enters a replaced name
(homonym) into the Quick Search on the splashpage? Right now, if you
enter the genus Cavia, it returns the Quarternary occurrences for the
guinea pig genus. Then, when you click "show more details", it asks to
confirm if you want info for the mammal genus Cavia, the mammal subgenus
C. (Cavia), or the (now replaced) trilobite genus Cavia. It would be
better if the "clarification" page proceeded the summary page.

**Comment by vjpsyverson** [comment]
Also "Cavia" and "cavia" in this search box produce different results.

@jczaplew , what is the original intended functioning of this component? What should it return?
Depending on the answer to this: @mmcclenn , can we just make this work on the same code as the Navigator quick search?

**Comment by jczaplew** [comment]
I am not sure. I was not involved in its development.

**Comment by vjpsyverson** [comment]
I'd like to address this by changing the search box to (a) function with a dropdown menu the same as the Navigator quick search (this is done in commit #56) and (b) have that dropdown menu send an oid to the search routine, instead of using the actual name string, so that homonyms are taken care of right at the beginning. 

Changing the issue name correspondingly.

(original name: "dealing with homonyms")

**Comment by vjpsyverson** [comment]
I think this is totally functional for the next version. Closing now. It'll be live on next push.
