### ISSUE TITLE
Add Partner Organizations page linked in About pull-down menu

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/splash_page#50]
Let's add another item to this menu for "Partner Organizations". Let's start with the following:

iDigBio
PaleoWire
Neotoma
Macrostrat
Mancos
Flyover Country

**Comment by vjpsyverson** [comment]
I think Flyover Country and Mancos are better suited in their current location under Resources/Apps, but for the other four definitely.

**Comment by vjpsyverson** [comment]
Working on this right now. What do you want this page to look like?

Alternatively, I could add another category to the resources page.

**Comment by vjpsyverson** [comment]
Take a look. I haven't written the text yet (it's still lorem ipsum) but you should tell me if you like the layout. Also, if you want to write the text I'd be happy to put that in instead, since I don't really understand why these specific organizations...

(you'll see that I left Mancos/Flyover/Rockd in the Mobile Apps category on Resources instead)

**Comment by vjpsyverson** [comment]
@markuhen, want to take a look? (https://training.paleobiodb.org/#/partners) 

Note lorem ipsum! Please give me some real text or give me guidelines to write it myself.

**Comment by vjpsyverson** [comment]
Done. It's got all Mark's requested entities as of July 2017 in it and is pushing with the update today.

Note: This is not a smart page. Entries have to be added manually in HTML.
